"""Deformation-search infrastructure for Track A (CLAUDE.md §6.1).

Per Claude (web) Q6 ruling 2026-04-29:

- **Q6a** Face-merge formalism: enumerate pairs of children in a
  σ-dissection that share a face; the merged tile is the polyhedron
  formed by removing the shared face. Vertex perturbation and
  parametric families are deferred secondary tools.
- **Q6b** Brute-force enumeration with cheap prioritisation filters
  applied before pillar-2 BFS (combinatorial PF feasibility, face-
  count sanity, vertex-class compatibility).
- **Q6c** Auto-generate ``candidates/<name>/fourth_pillar.py`` stub
  for every face-merge candidate at scaffold time, regardless of
  pillar status. The directory tree records every candidate
  *considered*, not just every candidate *surviving*.

This module is the entry point for Phase 1.5 of the roadmap. It does
not run any pillar checks itself — it produces candidates and helpers
that the existing ``hierarchy.aperiodicity_witness`` consumes.
"""

from __future__ import annotations

from pathlib import Path

__all__ = [
    "scaffold_merge_candidate",
]


_FOURTH_PILLAR_TEMPLATE = '''"""Fourth-pillar stub for the {display_name} merge candidate.

**Status: scaffold-time stub.** Generated by
``apeiron.deformation.scaffold_merge_candidate`` per Claude (web)'s
Q6c 2026-04-29 ruling. Two reasons for an auto-generated stub:

1. *Exercise the ``FourthPillarArgument`` protocol's import path*
   for every candidate — a missing module would surface only at
   pillar-4 time, potentially weeks after scaffold.
2. *Capture the geometric context* while it's fresh. The candidate
   was discovered as a face-merge of {parent_summary}; the proof
   approach for pillar 4 is recorded below.

**Pillar-4 approach (proposed, unverified).** {pillar_4_approach}

If this candidate survives pillars 1, 2, 3 — verified by
``apeiron.hierarchy.aperiodicity_witness`` — pillar 4 graduates from
this stub to a concrete implementation. Until then, both methods
raise ``NotImplementedError`` with the candidate's discovery
context.
"""

from __future__ import annotations

from apeiron.corona import CoronaConfig
from apeiron.hierarchy import (
    FourthPillarArgument,
    HierarchicalCounterexample,
    HierarchicalWitness,
)


class {class_name}(FourthPillarArgument):
    """Stub ``FourthPillarArgument`` for the {display_name} candidate."""

    _CONTEXT = (
        "Face-merge candidate from {parent_summary}; "
        "shared face: {shared_face_description}."
    )

    def local_configurations(self) -> frozenset[CoronaConfig]:
        raise NotImplementedError(
            "Pillar-4 local-configuration enumeration not yet "
            f"encoded for {{self._CONTEXT}}"
        )

    def verify_hierarchical(
        self, _config: CoronaConfig,
    ) -> HierarchicalWitness | HierarchicalCounterexample:
        raise NotImplementedError(
            "Pillar-4 hierarchical verification not yet "
            f"encoded for {{self._CONTEXT}}"
        )
'''


def _to_pascal_case(name: str) -> str:
    """Convert a snake_case or hyphen-case identifier to PascalCase
    for class naming. ``"danzer_merge_ab"`` -> ``"DanzerMergeAb"``.
    """
    parts = name.replace("-", "_").split("_")
    return "".join(p.capitalize() for p in parts if p)


def scaffold_merge_candidate(
    name: str,
    parent_letters: tuple[str, ...],
    shared_face_description: str,
    *,
    pillar_4_approach: str = (
        "Pillar 4 would require showing every face-to-face tiling by "
        "the merged tile arises from the ABCK hierarchy. Likely "
        "approach: extend Frettlöh Theorem 1.2's blue-edge mirror "
        "rule to account for the merged geometry."
    ),
    candidates_dir: Path = Path("candidates"),
) -> Path:
    """Create ``candidates/<name>/`` with an auto-generated
    ``fourth_pillar.py`` stub.

    Parameters
    ----------
    name
        Directory-safe name for the candidate, e.g.
        ``"danzer_merge_ab_face_3"``. Used both as the directory
        name and (PascalCase'd) as the ``FourthPillarArgument``
        subclass name.
    parent_letters
        The ABCK letters of the two prototiles being merged, e.g.
        ``("A", "B")``. Recorded in the stub's docstring for
        traceability.
    shared_face_description
        Human-readable description of the shared face, e.g.
        ``"face 2 of A coincides with face 0 of B at translation
        ½(τ², τ², τ²)"``. Appears in the stub's ``_CONTEXT`` string.
    pillar_4_approach
        Proposed approach to pillar 4 for this candidate. Defaults
        to a Frettlöh-style blue-edge mirror generalisation; pass
        a candidate-specific approach when one is known.
    candidates_dir
        Where to create the candidate directory. Defaults to
        ``candidates/`` at the project root.

    Returns
    -------
    Path
        The created candidate directory. The caller can then write
        the merged-tile JSON, substitution rule, etc., into it.

    Notes
    -----
    Per Q6c, called once per face-merge candidate *discovered* —
    not per candidate that survives pillar checks. This is the right
    research record to keep: every candidate considered has a
    directory, every directory has a fourth-pillar stub, every stub
    documents the discovery context. Survivors graduate to manual
    pillar-4 work.

    Raises
    ------
    FileExistsError
        If ``candidates_dir / name`` already exists. To rebuild a
        candidate, the caller deletes the directory first — a
        deliberate choice to prevent accidental overwriting of
        partial pillar-4 work.
    """
    if not name or "/" in name or name.startswith("."):
        raise ValueError(
            f"name must be a directory-safe identifier; got {name!r}"
        )
    candidate_dir = candidates_dir / name
    if candidate_dir.exists():
        raise FileExistsError(
            f"{candidate_dir} already exists. Delete it first to rebuild."
        )
    candidate_dir.mkdir(parents=True, exist_ok=False)

    parent_summary = "+".join(parent_letters)
    display_name = name
    class_name = _to_pascal_case(name) + "FourthPillar"

    fourth_pillar_text = _FOURTH_PILLAR_TEMPLATE.format(
        display_name=display_name,
        parent_summary=parent_summary,
        pillar_4_approach=pillar_4_approach,
        shared_face_description=shared_face_description,
        class_name=class_name,
    )
    (candidate_dir / "fourth_pillar.py").write_text(fourth_pillar_text)
    (candidate_dir / "__init__.py").write_text(
        f'"""Merge candidate {display_name}: {parent_summary}.\n\n'
        f"Auto-scaffolded by ``apeiron.deformation.scaffold_merge_candidate``.\n"
        f'"""\n'
    )
    return candidate_dir
